name: Generate and publish Sphinx documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dependencies
      run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev doxygen
        && sudo apt install sphinx-doc
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install sphinx-sitemap
        && pip3 install exhale
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build docs
      run: cmake --build ${{github.workspace}}/build -t sphinxdocs
        && touch docs/_build/docs_sphinx/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: docs/_build/docs_sphinx/
